name: k6 smoke

on:
  workflow_dispatch:             
  pull_request:
    branches: [ main ]
    paths:
      - 'test/k6/**'
      - '.github/workflows/k6-smoke.yml'
  push:
    branches: [ tools/k6-clean ] 

jobs:
  k6:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup k6
        uses: grafana/setup-k6-action@v1
      - name: Run k6 smoke test (default localhost)
        env:
          TARGET_URL: http://localhost:4567/
        run: k6 run --summary-export k6-summary.json test/k6/smoke.js
      - name: Upload k6 summary artifact
        uses: actions/upload-artifact@v4
        with:
          name: k6-summary
          path: k6-summary.json

